# @name login
POST http://localhost:8081/autenticacao/login
Content-Type: application/json

{
  "email": "admin@autobots.com",
  "senha": "123456"
}

@JWT = {{login.response.body.token}}

### Cadastrar um novo veiculo
POST http://localhost:8083/1/veiculo/cadastrar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "tipo": "SEDAN",
  "modelo": "Civic",
  "placa": "XYZ-9876",
  "proprietarioId": 2,
  "empresaId": 1
}

### Obter todos os veiculos
GET http://localhost:8083/1/veiculos
Authorization: Bearer {{JWT}}

### Obter um veiculo específico
GET http://localhost:8083/1/veiculo/1
Authorization: Bearer {{JWT}}

### Atualizar um veiculo
PUT http://localhost:8083/1/veiculo/atualizar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 1,
  "tipo": "SEDAN",
  "modelo": "Honda Civic",
  "placa": "XYZ-9876"
}

### Excluir um veiculo
DELETE http://localhost:8083/1/veiculo/excluir
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 1
}