version: '3.8'

services:
  autenticacao_mysql:
    image: mysql:8.0
    container_name: autenticacao_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: autenticacao_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3307:3306"
    volumes:
      - autenticacao_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - autenticacao_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  usuarios_mysql:
    image: mysql:8.0
    container_name: usuarios_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: usuarios_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3308:3306"
    volumes:
      - usuarios_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - usuarios_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  veiculos_mysql:
    image: mysql:8.0
    container_name: veiculos_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root123
      MYSQL_DATABASE: veiculos_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123
    ports:
      - "3309:3306"
    volumes:
      - veiculos_mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - veiculos_network
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

volumes:
  autenticacao_mysql_data:
  usuarios_mysql_data:
  veiculos_mysql_data:


networks:
  autenticacao_network:
    driver: bridge

  veiculos_network:
    driver: bridge

  usuarios_network:
    driver: bridge
