# @name login
POST http://localhost:8081/autenticacao/login
Content-Type: application/json

{
  "email": "admin@autobots.com",
  "senha": "123456"
}

@JWT = {{login.response.body.token}}

### Cadastrar uma nova venda
POST http://localhost:8085/1/venda/cadastrar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "cadastro": "2025-05-31",
  "clienteId": 2,
  "vendedorId": 5,
  "servicosIds": [1],
  "mercadoriasIds": [1],
  "veiculoId": 1
}

### Obter todas as vendas
GET http://localhost:8085/1/vendas?dataInicio=2020-01-01&dataFim=2025-01-03
Authorization: Bearer {{JWT}}

### Obter uma venda específica
GET http://localhost:8085/1/venda/2
Authorization: Bearer {{JWT}}

### Atualizar uma venda
PUT http://localhost:8085/1/venda/atualizar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 1,
  "cadastro": "2020-01-01",
  "clienteId": 2,
  "vendedorId": 5,
  "servicosIds": [1],
  "mercadoriasIds": [1],
  "veiculoId": 1
}

### Excluir uma venda
DELETE http://localhost:8085/1/venda/excluir
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 1
}