### Cadastrar uma nova mercadoria
POST http://localhost:8080/1/mercadoria/cadastrar
Content-Type: application/json

{
  "validade": "2030-01-01",
  "fabricao": "2025-01-01",
  "cadastro": "2025-01-01",
  "nome": "Óleo de motor",
  "quantidade": 10,
  "valor": 100,
  "descricao": "Óleo de motor 10W40"
}

### Obter todas as mercadorias
GET http://localhost:8080/1/mercadorias

### Obter uma mercadoria específica
GET http://localhost:8080/1/mercadoria/1

### Atualizar uma mercadoria
PUT http://localhost:8080/1/mercadoria/atualizar
Content-Type: application/json

{
  "id": 1,
  "validade": "2045-01-01",
  "fabricao": "2012-01-01",
  "cadastro": "2025-01-01",
  "nome": "Cera de motor",
  "quantidade": 20,
  "valor": 200,
  "descricao": "Cera de motor 40W10"
}

### Excluir uma mercadoria
DELETE http://localhost:8080/1/mercadoria/excluir
Content-Type: application/json

{
  "id": 1,
  "validade": "2045-01-01",
  "fabricao": "2012-01-01",
  "cadastro": "2025-01-01",
  "nome": "Cera de motor",
  "quantidade": 20,
  "valor": 200,
  "descricao": "Cera de motor 40W10"
}