### Cadastrar um novo veiculo
POST http://localhost:8080/veiculo/cadastrar
Content-Type: application/json

{
  "tipo": "SEDAN",
  "modelo": "Civic",
  "placa": "XYZ-9876"
}

### Obter todos os veiculos
GET http://localhost:8080/veiculos

### Obter um veiculo específico
GET http://localhost:8080/veiculo/1

### Atualizar um veiculo
PUT http://localhost:8080/veiculo/atualizar
Content-Type: application/json

{
  "id": 1,
  "tipo": "SEDAN",
  "modelo": "Honda Civic",
  "placa": "XYZ-9876"
}

### Excluir um veiculo
DELETE http://localhost:8080/veiculo/excluir
Content-Type: application/json

{
  "id": 2,
  "tipo": "SEDAN",
  "modelo": "Honda Civic",
  "placa": "XYZ-9876"
}