### Cadastrar documento
POST http://localhost:8080/documento/cadastro
Content-Type: application/json

{
  "tipo": "CPF",
  "numero": "1234567899"
}


### Obter documentos
GET http://localhost:8080/documento/documentos

### Obter documento
GET http://localhost:8080/documento/documento/1

### Atualizar documento
PUT http://localhost:8080/documento/atualizar
Content-Type: application/json

{
  "id": 1,
  "tipo": "CNPJ",
  "numero": "9999999999999"
}

### Excluir documento
DELETE http://localhost:8080/documento/excluir
Content-Type: application/json

{
  "id": 1
} 