# @name login
POST http://localhost:8080/autenticacao/login
Content-Type: application/json

{
  "nomeUsuario": "gerente-usuario",
  "senha": "123456"
}

@JWT = {{login.response.body.token}}

### Cadastrar um novo serviço
POST http://localhost:8080/1/servico/cadastrar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "nome": "Troca de óleo",
  "valor": 120,
  "descricao": "Troca de óleo do motor"
}

### Obter todos os serviços
GET http://localhost:8080/1/servicos
Authorization: Bearer {{JWT}}

### Obter um serviço específico
GET http://localhost:8080/1/servico/1
Authorization: Bearer {{JWT}}

### Atualizar um serviço
PUT http://localhost:8080/1/servico/atualizar
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 1,
  "nome": "Alinhamento e balanceamento",
  "valor": 150,
  "descricao": "Serviço de alinhamento e balanceamento das rodas"
}

### Excluir um servico
DELETE http://localhost:8080/1/servico/excluir
Content-Type: application/json
Authorization: Bearer {{JWT}}

{
  "id": 1
}